# Generated by Django 5.0.1 on 2024-05-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionMainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_title', models.CharField(blank=True, max_length=255, null=True)),
                ('motion_description', models.TextField()),
                ('motion_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('motion_video', models.FileField(upload_to='videos/')),
                ('motion_publish_date', models.DateTimeField(auto_now_add=True)),
                ('motion_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-motion_publish_date'],
            },
        ),
    ]
