# Generated by Django 5.0.1 on 2024-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionmainpost',
            name='motion_video',
        ),
        migrations.AddField(
            model_name='motionmainpost',
            name='motion_img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
