# Generated by Django 5.0.1 on 2024-05-24 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0002_remove_motionmainpost_motion_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_motion_title', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_motion_description', models.TextField()),
                ('blog_motion_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('blog_motion_img', models.ImageField(upload_to='blog_images/')),
                ('blog_motion_publish_date', models.DateTimeField(auto_now_add=True)),
                ('blog_motion_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blog_motion_publish_date'],
            },
        ),
    ]
